# Generated by Django 2.1.4 on 2019-01-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Academic Year ID')),
                ('academic_year_name', models.CharField(max_length=50, verbose_name='Academic Year Name')),
                ('academic_year_date_start', models.DateField(verbose_name='Academic Year Start Date')),
                ('academic_year_date_end', models.DateField(verbose_name='Academic Year End Date')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['academic_year_date_start'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Semester ID')),
                ('semester_name', models.CharField(max_length=50, verbose_name='Name')),
                ('semester_date_start', models.DateField(verbose_name='Start Date')),
                ('semester_date_end', models.DateField(verbose_name='End Date')),
                ('semester_isSummerTerm', models.BooleanField(verbose_name='Is Summer Term')),
                ('semester_isInUse', models.BooleanField(verbose_name='Is in Use')),
                ('semester_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.AcademicYear')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['semester_academic_year', 'semester_name'],
            },
        ),
    ]
