# Generated by Django 2.1.4 on 2019-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_mobile',
            field=models.BigIntegerField(verbose_name='Teacher mobile'),
        ),
    ]
