# Generated by Django 2.1.4 on 2019-01-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('academic_level_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_level_name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'ordering': ['academic_level_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('course_theory_load', models.IntegerField(default=0, verbose_name='Theory Load')),
                ('course_lab_load', models.IntegerField(default=0, verbose_name='Lab Load')),
                ('course_tutorial_load', models.IntegerField(default=0, verbose_name='Tutorial Load')),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AcademicLevel')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['speciality', 'academic_level', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
                'ordering': ['speciality_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Speciality'),
        ),
    ]
