# Generated by Django 2.1.4 on 2019-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='speciality_name_ar',
            field=models.CharField(default='', max_length=50, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
