# Generated by Django 2.1.4 on 2019-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190103_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name_ar',
            field=models.CharField(default='', max_length=100, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
