# Generated by Django 2.1.4 on 2019-01-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR', '0001_initial'),
        ('courses', '0001_initial'),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False, verbose_name='College ID')),
                ('college_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='College Name')),
                ('college_name_ar', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='College Name (Arabic)')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college_name', 'college_location'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('department_name_ar', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Department Name (Arabic)')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name', 'department_location'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Location ID')),
                ('location_name_ar', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='location Name (arabic)')),
                ('location_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='location Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Section ID')),
                ('section_code', models.IntegerField(unique=True, verbose_name='Section Code')),
                ('section_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Section Course')),
                ('section_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='Section Department')),
                ('section_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periods.Semester', verbose_name='Section Semester')),
                ('section_teachers', models.ManyToManyField(blank=True, to='HR.Teacher', verbose_name='Section Teachers')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['section_course', 'section_code'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_name_ar'], name='departments_locatio_714e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_name'], name='departments_locatio_66ec5f_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.College', verbose_name='Department Location'),
        ),
        migrations.AddField(
            model_name='college',
            name='college_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Location', verbose_name='College Location'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_code'], name='departments_section_8d9052_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name'], name='departments_departm_c4f7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name_ar'], name='departments_departm_f19921_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_name'], name='departments_college_a4864b_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_name_ar'], name='departments_college_a67adb_idx'),
        ),
    ]
