# Generated by Django 2.1.4 on 2018-12-15 10:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDocRequest',
            fields=[
                ('course_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('college', models.CharField(max_length=500, verbose_name='College Name')),
                ('department', models.CharField(max_length=500, verbose_name='Departement Name')),
                ('course', models.CharField(max_length=500, verbose_name='Couse Name')),
                ('section', models.IntegerField(verbose_name='Section Number')),
                ('maxgrades', models.IntegerField(default=100, verbose_name='Full Grade')),
                ('student_grades', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doc_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_std_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_skewness', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_correlation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('histogram', models.FileField(max_length=1024, upload_to='media/')),
                ('doc_explanation', models.TextField(verbose_name='\u202b\u202aExplanation\u202c\u202c \u202b\u202aand\u202c\u202c \u202b\u202athe\u202c\u202c \u202b\u202arecommendations\u202c\u202c')),
                ('teacher_name', models.CharField(max_length=500, verbose_name='Teacher Name')),
                ('teacher_email', models.EmailField(max_length=500, verbose_name='Teacher Email')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
    ]
