# Generated by Django 2.1.4 on 2018-12-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='course',
            field=models.CharField(max_length=500, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='department',
            field=models.CharField(max_length=500, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='student_grades',
            field=models.CharField(max_length=2048, verbose_name='Grades'),
        ),
    ]
