# Generated by Django 2.1.4 on 2018-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20181215_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='histogram',
            field=models.FileField(max_length=1024, upload_to='data/media/'),
        ),
    ]
