# Generated by Django 2.1.4 on 2019-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20190103_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_ttest_annova_type',
            field=models.CharField(max_length=100, verbose_name='Correlation Type'),
        ),
    ]
