# Generated by Django 2.1.4 on 2018-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20181216_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('college_name', models.CharField(max_length=100, unique=True, verbose_name='College Name')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('course_code', models.CharField(max_length=8, unique=True, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='Course Name')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('department_name', models.CharField(max_length=100, unique=True, verbose_name='College Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_name'],
            },
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.AlterModelOptions(
            name='sectiondocrequest',
            options={'ordering': ['college', 'department', 'course', 'section'], 'verbose_name': 'Course Analysis Report', 'verbose_name_plural': 'Course Analysis Reports'},
        ),
    ]
