# Generated by Django 2.1.4 on 2019-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20190105_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseanalysisreport',
            name='remarks',
            field=models.TextField(default='', verbose_name='Remarks\u202c\u202c'),
        ),
        migrations.AddField(
            model_name='sectionanalysisreport',
            name='remarks',
            field=models.TextField(default='', verbose_name='Remarks\u202c\u202c'),
        ),
    ]
