# Generated by Django 2.1.4 on 2018-12-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_course_course_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Course Name (arabic)'),
        ),
    ]
