# Generated by Django 2.1.4 on 2018-12-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_auto_20181216_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Course Code'),
        ),
    ]
