# Generated by Django 2.1.4 on 2018-12-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_auto_20181216_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Location ID')),
                ('location_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='location Name')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Section ID')),
                ('course_code', models.IntegerField(unique=True, verbose_name='Section Code')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['section_course', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Section ID')),
                ('teacher_name', models.CharField(max_length=100, unique=True, verbose_name='Teacher name')),
                ('teacher_name_ar', models.CharField(max_length=100, unique=True, verbose_name='Teacher name (arabic)')),
                ('teacher_mobile', models.IntegerField(unique=True, verbose_name='Teacher mobile')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['teacher_name', 'teacher_name_ar'],
            },
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['college_name', 'college_location'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_department', 'course_code', 'course_name', 'course_name_ar'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name', 'department_location'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Department', verbose_name='Course Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.College', verbose_name='Department Location'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='College ID'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Course', verbose_name='Section Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Teacher', verbose_name='Section Teacher'),
        ),
        migrations.AddField(
            model_name='college',
            name='college_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.Location', verbose_name='College Location'),
        ),
    ]
