# Generated by Django 2.1.4 on 2018-12-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_auto_20181220_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section_course', 'section_code'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='course_code',
            new_name='section_code',
        ),
    ]
