# Generated by Django 2.1.4 on 2018-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_auto_20181220_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_mobile',
            field=models.IntegerField(verbose_name='Teacher mobile'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=100, verbose_name='Teacher name'),
        ),
    ]
