# Generated by Django 2.1.4 on 2018-12-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_auto_20181220_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='location Name (arabic)'),
        ),
    ]
