# Generated by Django 2.1.4 on 2018-12-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_auto_20181221_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('translation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Section ID')),
                ('translation_ar', models.CharField(max_length=100, unique=True, verbose_name='Translation AR')),
                ('translation_en', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Translation EN')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['translation_ar'],
            },
        ),
    ]
