# Generated by Django 2.1.4 on 2018-12-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0014_auto_20181221_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_teacher',
        ),
        migrations.AddField(
            model_name='section',
            name='section_teachers',
            field=models.ManyToManyField(blank=True, to='measurement.Teacher', verbose_name='Section Teachers'),
        ),
    ]
