# Generated by Django 2.1.4 on 2018-12-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0017_auto_20181221_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiondocrequest',
            name='teacher_email',
        ),
        migrations.RemoveField(
            model_name='sectiondocrequest',
            name='teacher_name',
        ),
    ]
