# Generated by Django 2.1.4 on 2018-12-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0018_auto_20181221_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_course', to='measurement.Course', verbose_name='Section Course'),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_section', to='measurement.Section', verbose_name='Section'),
        ),
    ]
