# Generated by Django 2.1.4 on 2018-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0019_auto_20181221_2029'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_name'], name='measurement_college_d1ea94_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['college_name_ar'], name='measurement_college_e2950c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='measurement_course__1121a4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='measurement_course__be593e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name_ar'], name='measurement_course__6ec2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name'], name='measurement_departm_df1508_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['department_name_ar'], name='measurement_departm_961b50_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_name_ar'], name='measurement_locatio_401a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_name'], name='measurement_locatio_1fa6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['section_code'], name='measurement_section_2bd634_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_name'], name='measurement_teacher_18300e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_name_ar'], name='measurement_teacher_cdfe67_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_email'], name='measurement_teacher_e22624_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['translation_ar'], name='measurement_transla_8c2a76_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['translation_en'], name='measurement_transla_cc6d7a_idx'),
        ),
    ]
