# Generated by Django 2.1.4 on 2018-12-23 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0020_auto_20181222_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDocRequest',
            fields=[
                ('course_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_std_deviation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_skewness', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_correlation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('doc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('doc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('histogram', models.FileField(max_length=1024, upload_to='data/media/')),
                ('doc_ttest_annova_type', models.CharField(max_length=100, unique=True, verbose_name='Correlation Type')),
                ('doc_ttest_annova_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Course Correlation Value')),
                ('doc_ttest_annova_sig', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Course Correlation Significance')),
                ('doc_explanation', models.TextField(verbose_name='\u202b\u202aExplanation\u202c\u202c \u202b\u202aand\u202c\u202c \u202b\u202athe\u202c\u202c \u202b\u202arecommendations\u202c\u202c')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Analysis Report',
                'verbose_name_plural': 'Course Analysis Reports',
                'ordering': ['course'],
            },
        ),
        migrations.AlterModelOptions(
            name='sectiondocrequest',
            options={'ordering': ['section'], 'verbose_name': 'Section Analysis Report', 'verbose_name_plural': 'Section Analysis Reports'},
        ),
        migrations.RenameField(
            model_name='sectiondocrequest',
            old_name='course_doc_id',
            new_name='section_doc_id',
        ),
    ]
