# Generated by Django 2.1.4 on 2018-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0021_auto_20181223_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_correlation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_skewness',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_std_deviation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_ttest_annova_sig',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Course Correlation Significance'),
        ),
        migrations.AlterField(
            model_name='coursedocrequest',
            name='doc_ttest_annova_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Course Correlation Value'),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_correlation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_mean',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_skewness',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondocrequest',
            name='doc_std_deviation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
