# Generated by Django 2.1.4 on 2018-12-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0022_auto_20181223_0800'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursedocrequest',
            index=models.Index(fields=['course'], name='measurement_course__860b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='sectiondocrequest',
            index=models.Index(fields=['section'], name='measurement_section_513290_idx'),
        ),
    ]
